---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The rabbitmq needs access to hostvars for all containers in order
# to set the values in /etc/hosts. We therefore collect all host/container
# facts before continuing.
- name: Gather facts
  hosts: "rabbitmq_all"
  remote_user: root
  gather_facts: true

# The cluster must be stopped when doing major/minor upgrades
# http://www.rabbitmq.com/clustering.html#upgrading
- name: Stop RabbitMQ nodes that are not the upgrader
  hosts: "rabbitmq_all[1:]"
  serial: 1
  any_errors_fatal: true
  remote_user: root
  tasks:
    - name: "Stop RabbitMQ"
      service:
        name: "rabbitmq-server"
        state: "stopped"
      when:
        - (rabbitmq_upgrade | default(false)) | bool

- name: Deploy Rabbitmq
  hosts: rabbitmq_all
  serial: 1
  remote_user: root
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: "rabbitmq_server"
  vars_files:
    - test-vars.yml
